repos:
- repo: https://github.com/psf/black
  rev: 24.10.0  # Latest version of Black
  hooks:
    - id: black
      args: [--line-length=150]
      files: ^tests-functional/.*\.py$
      # Black: Automatically formats Python code to adhere to its strict style guidelines.
      # - Ensures consistent code formatting across the project.
      # - Helps maintain readability and avoids debates about style in code reviews.

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.388  # Version of Pyright used
  hooks:
    - id: pyright
      files: ^tests-functional/.*\.py$
      # Pyright: A static type checker for Python.
      # - Validates type hints and ensures type correctness in code.
      # - Identifies type mismatches, missing imports, and potential runtime errors.
      # - Ensures better type safety and helps catch bugs early.

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1  # Latest version of Flake8
  hooks:
    - id: flake8
      args: ["--max-line-length=150"]
      files: ^tests-functional/.*\.py$
      # Flake8: A lightweight Python linter for style and syntax checking.
      # - Detects unused imports, undefined variables, and redefined functions (e.g., F811).
      # - Checks for adherence to Python coding standards (PEP 8).
      # - Helps maintain clean, bug-free code.
