services:
  status-backend:
    user: ${INTEGRATION_TESTS_DOCKER_UID}
    build:
      context: ../
      dockerfile: _assets/build/Dockerfile
      args:
        build_tags: gowaku_no_rln,enable_private_api
        build_target: status-backend
        build_flags: -cover
    entrypoint: [
      "status-backend",
      "--address", "0.0.0.0:3333",
    ]
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST --data '{\"jsonrpc\":\"2.0\",\"method\":\"net_version\",\"params\":[],\"id\":1}' -H 'Content-Type: application/json' http://0.0.0.0:3333 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 120
    environment:
      GOCOVERDIR: "/coverage/binary"
    volumes:
      - ./coverage/binary:/coverage/binary
    stop_signal: SIGINT
