version: "3.9"

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:0:0:1::/64"
          gateway: "fd00:0:0:1::1"

services:
  anvil:
    networks:
      - default

  deploy-sntv2:
    networks:
      - default

  deploy-communities-contracts:
    networks:
      - default

  status-backend:
    entrypoint: [
      "status-backend",
      "--address", "[::]:3333"
    ]
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST --data '{\"jsonrpc\":\"2.0\",\"method\":\"net_version\",\"params\":[],\"id\":1}' -H 'Content-Type: application/json' http://[::1]:3333 || exit 1"]
    networks:
      - default
