version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/24

services:
  anvil:
    networks:
      - default

  deploy-sntv2:
    networks:
      - default

  deploy-communities-contracts:
    networks:
      - default

  status-backend:
    entrypoint: [
      "status-backend",
      "--address", "0.0.0.0:3333"
    ]
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST --data '{\"jsonrpc\":\"2.0\",\"method\":\"net_version\",\"params\":[],\"id\":1}' -H 'Content-Type: application/json' http://0.0.0.0:3333 || exit 1"]
    networks:
      - default
